name: foodly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #dependencies
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.2
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  iconsax: ^0.0.8
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.5
  http: ^1.2.1
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  get_storage: ^2.1.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  country_picker: ^2.0.25
  logger: ^2.3.0
  gap: ^3.0.1
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

#assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/anime/
